### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by louisguitton** [louisguitton/friendly-broccoli#16]
* translate to spanish, french, egyptian if that makes sense using [this article](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiii-i18n-and-l10n)

**Comment by ghost** [comment]
Hello, if there isn't too many strings to translate I could help with the spanish translation. I will check out the article later.

**Comment by louisguitton** [comment]
Hi @makmm thanks for the nice proposition.
At the minute translation in not the priority, but I'll keep you in mind when we go for it.
